stackfolio/stackfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'stackfolio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('stackyelp.urls', namespace='stackyelp')),
)

stackfolio/stackyelp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from stackyelp import views

urlpatterns = patterns('',
	 url(r'^$', views.home, name='home'),
)

stackfolio/stackyelp/models.py
from django.db import models

# Create your models here.

stackfolio/stackyelp/views.py
from django.shortcuts import render
from stackfolio import yelphelp as yh

def home(request):

	if request.GET.get('location', None):
		token = yh.get_access_token()
		search_term = request.GET.get('search_term', None)
		location = request.GET.get('location', None)
		results = yh.quick_search(token, search_term, location)

		average_price = yh.average_price(results)
		average_rating = yh.average_rating(results)
		
		image_dict = {}
		for r in results:
			image_dict[r['name']] = (r['image_url'],r['url'])

		return render(request, 'stackyelp/home.html', {
				'image_dict':image_dict,
				'average_price':average_price,
				'average_rating':average_rating,
				'search_term':search_term,
				'location':location,
				'result_count': len(results),
				})

	return render(request, 'stackyelp/home.html')

stackfolio/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>{% block title %}Stackfolio Yelp App{% endblock title %}</title>
	{% block stylesheets %}
	<link rel="stylesheet" href="{% static 'stackfolio/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'stackfolio/theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'stackfolio/styling.css' %}" />
	<link rel="stylesheet" href="{% static 'stackfolio/fa/css/font-awesome.css' %}" />
	{% endblock stylesheets %}
</head>

{% block scriptload %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'stackfolio/js/bootstrap.min.js' %}"></script>
<script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
<script src="https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.min.js"></script>
{% endblock scriptload %}


<body role='document'>
    <!-- Navigation -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'stackyelp:home' %}">
                	<span class='fa fa-home fa-lg'></span>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                	<li>
                		<a href="https://github.com/souldeux/stackfolio_project">project repo</a>
                	</li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </div>


{% if messages %}
<div class='container'>
	<ul class="messages">
	{% for message in messages %}
	<li id="message_{{ forloop.counter}}"
		{% if message.tags %} class="alert alert-{{ message.tags }}"
		{% endif %}>
		{{ message }}
	</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

<div class="container theme-showcase" role="main">
	{% block body %}
	{% endblock body %}
</div>

<hr>
{% block footer %}
<div class="container marketing">
<footer>
	<p class="pull-right"><a href="#">Back to top</a></p>
	<p class='small text-muted'>&copy; 2014 - <script>document.write(new Date().getFullYear());</script> Nick Perry</p>
</footer>
</div>
{% endblock footer %}


  </body>
</html>

stackfolio/templates/stackyelp/home.html
{% extends 'base.html' %}

{% block body %}
<div class='row'>
	<div class='col-sm-5'>
		<h1>What's The Eats?</h1>
		<form method='get' action=''>
			<div class='form-group'>
				<label for='search_term'>what</label>
				<input type='text' class='form-control' name='search_term' placeholder="examples: deli, starbucks" required>
			</div>
			<div class='form-group'>
				<label for='location'>where</label>
				<input type='text' class='form-control' name='location' placeholder="examples: atlanta, LA" required>
			</div>
			<button type='submit' class='btn btn-success'>do thing</button>
		</form>
	</div>

	<div class='col-sm-7'>
		{% if not average_price %}
		<div class='jumbotron'>
			<p>Scientific studies show that you only need to know three things about any place on Earth in order
				to determine whether or not it's a Good Place For You:</p>
				<li>Is the food good?</li>
				<li>Is it affordable?</li>
				<li>Is it photogenic?</li>
				<br>
			<p align='center'>We've got you covered. Let's explore.</p>
		</div>
		{% else %}
		<div class='row'>
			<div class='stat-panel row well'>
				<div class='col-sm-6'>
					<h2>You searched for...</h2>
					<p>Search Term: <span class='label label-info'>{{search_term}}</span></p>
					<p>Location: <span class='label label-info'>{{location}}</span></p>
				</div>
				<div class='col-sm-6'>
					<h2>About Your Results</h2>
					<p>Results (Max 50): <span class='label label-info'>{{result_count}}</span></p>
					<p>Average Price (1-4): <span class='label label-info'>{{average_price}}</span></p>
					<p>Average Rating (1-5): <span class='label label-info'>{{average_rating}}</span></p>
				</div>
			</div>
		</div>
		{% endif %}
	</div>
</div>

<div class='row'>
	<div class='masonry'>
		{% for name, tuple in image_dict.items %}
			<div id='grid-selector' class='item-200'>
				<div class='hovereffect'>
					<img src="{{tuple.0}}" class='img-responsive' />
					<div class='overlay'>
						<a href="{{tuple.1}}" target="_blank" style="text-decoration:none;">
							<h2>{{name}}</h2>
						</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

<script type='text/javascript'>
var $g = $('.masonry').imagesLoaded(function(){
	$g.masonry({
		itemSelector: '.item-200',
		columnWidth: 100,
		fitWidth: true,
	});
});
</script>


{% endblock %}